### ISSUE TITLE
after installing Addon and opening chrome store, still there is "available on chrome" option is available

### ISSUE THREAD

**Issue by danyalblogger** [Noitidart/Chrome-Store-Foxified#42] opened 2016-09-04 13:56 UTC

**Comment by Noitidart** [comment] 2016-09-05 08:43
Thanks for opening the issue @danyalblogger - I'll test this and get back to you soon.

**Comment by Noitidart** [comment] 2016-09-13 16:26
@danyalblogger for the last week I tried to reproduce this. I could not. What version of the addon are you using? What version of Firefox?

I found that my addon does not work in Firefox 45, but it works in Firefox 46 and up.

**Comment by kvervo** [comment] 2016-10-11 20:57
@Noitidart having issues on Firefox 51.0a Developer Edition.

**Comment by bluebrainc** [comment] 2016-10-23 17:53
@kvervo 51.0a2 Developer Edition works for me.

**Comment by Noitidart** [comment] 2016-10-23 20:10
Whoops @kvervo  I missed your comment. Thanks to @bluebrainc  for bringing my attention to it.

I tested in 51.* and it also works. I have attached here a developer version, with console logging. Please install this and see if you notice anything odd in the browser console. If you don't see anything odd, please share with me the console output.

To install, please download the file, then rename it to xpi (github wouldn't let me upload xpi so i named it .zip). Then install DevPrefs addon - https://addons.mozilla.org/en-US/firefox/addon/devprefs/ - and then drag and drop this XPI into your Firefox.

[Chrome-Store-Foxified.zip](https://github.com/Noitidart/Chrome-Store-Foxified/files/546602/Chrome-Store-Foxified.zip)

**Comment by bluebrainc** [comment] 2016-10-23 20:49
@Noitidart I guess you mean @kvervo , but I 've done it in my installation too, again no problems installing and using it I think, but the console put out two errors ( [this Gist](https://gist.github.com/bluebrainc/478aeb5e815bc62268971822d5bab6d1) , lines 5 and 10).

**Comment by kvervo** [comment] 2016-10-23 21:15
@Noitidart thnx, the output from console.log is as follows:

```
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  jsapi:17:372
ReferenceError: reference to undefined property c.customSpecs[Learn More]  jsapi:23:418
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:14:245
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:17:309
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:17:324
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:18:22
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:18:510
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:19:105
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:67:424
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:68:385
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:166:259
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:190:387
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:190:410
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:211:278
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:213:767
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:220:150
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:250:294
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:328:267
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:328:389
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:461:127
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:463:514
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:465:122
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:483:263
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:484:228
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:484:251
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:548:166
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:553:171
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:566:97
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:589:473
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:674:189
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:683:466
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:694:62
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:701:78
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:746:296
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:752:426
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:753:325
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:775:306
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:812:184
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:812:374
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:848:154
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:857:32
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:863:396
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:902:363
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:939:49
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:961:335
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:967:191
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:985:109
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:994:462
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1023:355
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1035:53
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1049:320
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1095:165
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1132:208
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1150:322
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1197:425
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1207:382
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1228:95
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1250:250
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1256:178
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1265:79
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1276:222
ReferenceError: reference to undefined property window.external.startE[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:26:335
ReferenceError: reference to undefined property a[el][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:192:123
ReferenceError: reference to undefined property a.a[k][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:72:95
ReferenceError: reference to undefined property a.clientWidth[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:125:458
ReferenceError: reference to undefined property c.b[b][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:548:123
ReferenceError: reference to undefined property a.a[c][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:178:71
ReferenceError: reference to undefined property a.Ma.a[String(...)][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:223:303
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  platform.js:3:569
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  platform.js:5:1279
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  platform.js:28:219
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  platform.js:35:841
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  platform.js:47:991
ReferenceError: reference to undefined property a.push[Learn More]  platform.js:13:575
ReferenceError: reference to undefined property a.metaKey[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:137:405
ReferenceError: reference to undefined property this.c[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:307:118
ReferenceError: reference to undefined property this.h[a][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:469:73
ReferenceError: reference to undefined property this.M[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:336:187
ReferenceError: reference to undefined property a.u[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:997:12
ReferenceError: reference to undefined property a.a[b.toString(...)][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:73:321
ReferenceError: reference to undefined property a.c[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:77:459
ReferenceError: reference to undefined property this.B[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:1148:117
ReferenceError: reference to undefined property this.f[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:706:234
ReferenceError: reference to undefined property a.latestVersion[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:10:229
ReferenceError: reference to undefined property l[e][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:12:53
ReferenceError: reference to undefined property a[b][Learn More]  platform.js:7:404
ReferenceError: reference to undefined property H.bsh[Learn More]  platform.js:38:484
ReferenceError: reference to undefined property b.onload[Learn More]  platform.js:24:624
ReferenceError: reference to undefined property u(...)[a][Learn More]  platform.js:5:380
ReferenceError: reference to undefined property a.ao[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:414:92
ReferenceError: reference to undefined property a.Yb[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:232:22
SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead  default+en.I.js:73:33
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:146:1500
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:149:51
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:159:197
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:181:1326
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:182:88
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:185:158
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:191:542
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:209:424
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:225:1099
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:227:65
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:242:293
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:254:69
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:255:120
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:268:788
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:440:102
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:489:160
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:523:349
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:526:116
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  default+en.I.js:560:321
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:8:225
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:9:287
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:9:302
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:9:507
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:10:458
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:11:52
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:24:766
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:26:172
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:26:321
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:26:459
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:28:66
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:29:72
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:44:3
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:46:56
ReferenceError: reference to undefined property this.options.onLoadFinishedCallback[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:20:61
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:7:766
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:9:172
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:9:321
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:9:459
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:11:66
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:12:72
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:27:3
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:29:56
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:20:151
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:189:85
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:189:98
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:201:170
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:255:349
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:255:373
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:345:123
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:347:82
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:389:203
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:391:348
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:401:307
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:402:464
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:404:75
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:430:155
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:436:261
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:436:330
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:453:489
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:457:87
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:470:276
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:473:159
ReferenceError: reference to undefined property a.push[Learn More]  cb=gapi.loaded_0:21:466
ReferenceError: reference to undefined property (intermediate value).disableForceSecure[Learn More]  cb=gapi.loaded_0:44:167
ReferenceError: reference to undefined property c.useLegacyProtocol[Learn More]  cb=gapi.loaded_0:56:348
ReferenceError: reference to undefined property a.push[Learn More]  cb=gapi.loaded_0:30:40
ReferenceError: reference to undefined property window.external.startE[Learn More]  cb=gapi.loaded_0:409:363
ReferenceError: reference to undefined property _.pG[Learn More]  cb=gapi.loaded_1:2:1
ReferenceError: reference to undefined property c[g.toLowerCase(...)][Learn More]  cb=gapi.loaded_0:430:98
ReferenceError: reference to undefined property _.bb.ILI[Learn More]  cb=gapi.loaded_0:421:389
ReferenceError: reference to undefined property c.count[Learn More]  cb=gapi.loaded_1:8:243
ReferenceError: reference to undefined property f.db[Learn More]  cb=gapi.loaded_0:395:109
ReferenceError: reference to undefined property f.ecp[Learn More]  cb=gapi.loaded_0:395:206
ReferenceError: reference to undefined property this.Ea.rpcAddr[Learn More]  cb=gapi.loaded_0:179:222
ReferenceError: reference to undefined property a.Ea.retAddr[Learn More]  cb=gapi.loaded_0:179:307
ReferenceError: reference to undefined property this.Ea.origin[Learn More]  cb=gapi.loaded_0:179:417
ReferenceError: reference to undefined property this.Ea.frameName[Learn More]  cb=gapi.loaded_0:179:123
ReferenceError: reference to undefined property a.Ea.rpctoken[Learn More]  cb=gapi.loaded_0:176:323
ReferenceError: reference to undefined property a.Ea._popupWindow[Learn More]  cb=gapi.loaded_0:184:414
ReferenceError: reference to undefined property a.Ea.setRpcReady[Learn More]  cb=gapi.loaded_0:179:523
ReferenceError: reference to undefined property b.dir[Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:90:527
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:2:628
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:2:638
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:8:245
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:9:157
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:10:138
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:10:244
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:15:360
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:15:375
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:21:263
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:36:431
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:48:269
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  en.js:51:406
ReferenceError: reference to undefined property b.rating[Learn More]  en.js:46:165
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:69:725
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:69:1618
ReferenceError: reference to undefined property a[b][Learn More]  fastbutton:71:398
ReferenceError: reference to undefined property a.oid[Learn More]  cb=gapi.loaded_0:335:82
ReferenceError: reference to undefined property c.ariaLabel[Learn More]  cb=gapi.loaded_0:337:452
ReferenceError: reference to undefined property K[a][Learn More]  cb=gapi.loaded_0:55:263
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  1240234406-postmessagerelay.js:4:99
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rpc:shindig_random.js:1:707
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  rpc:shindig_random.js:1:1600
ReferenceError: reference to undefined property a[b][Learn More]  rpc:shindig_random.js:3:398
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:20:151
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:140:412
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:178:123
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:180:82
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:236:349
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:236:373
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:296:60
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:297:255
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:366:85
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:366:98
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:378:170
ReferenceError: reference to undefined property a.push[Learn More]  fastbutton:21:466
ReferenceError: reference to undefined property (intermediate value).disableForceSecure[Learn More]  fastbutton:51:167
ReferenceError: reference to undefined property f.useLegacyProtocol[Learn More]  fastbutton:64:6
ReferenceError: reference to undefined property c.useLegacyProtocol[Learn More]  fastbutton:63:348
ReferenceError: reference to undefined property this.Ea.id[Learn More]  fastbutton:350:332
ReferenceError: reference to undefined property a.Ea.rpctoken[Learn More]  fastbutton:353:323
ReferenceError: reference to undefined property this.Ea.iframeEl[Learn More]  fastbutton:356:679
ReferenceError: reference to undefined property this.Ea.url[Learn More]  fastbutton:350:161
ReferenceError: reference to undefined property a.Ea._popupWindow[Learn More]  fastbutton:361:414
ReferenceError: reference to undefined property a.Ea.setRpcReady[Learn More]  fastbutton:356:523
ReferenceError: reference to undefined property a.push[Learn More]  fastbutton:37:40
ReferenceError: reference to undefined property d.before_eval_cb[Learn More]  fastbutton:77:462
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:44:289
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:60:136
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:60:159
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:72:380
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:97:287
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:98:170
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:112:331
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:134:206
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:151:150
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:165:326
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  fastbutton:184:173
ReferenceError: reference to undefined property b.$a[a][Learn More]  fastbutton:151:101
ReferenceError: reference to undefined property this.L[f][Learn More]  fastbutton:56:402
ReferenceError: reference to undefined property a[Gc][Learn More]  fastbutton:61:337
SyntaxError: test for equality (==) mistyped as assignment (=)?[Learn More]  cb=gapi.loaded_0:20:151
ReferenceError: reference to undefined property a.push[Learn More]  cb=gapi.loaded_0:21:466
ReferenceError: reference to undefined property (intermediate value).disableForceSecure[Learn More]  cb=gapi.loaded_0:44:167
ReferenceError: reference to undefined property f.useLegacyProtocol[Learn More]  cb=gapi.loaded_0:57:6
ReferenceError: reference to undefined property c.useLegacyProtocol[Learn More]  cb=gapi.loaded_0:56:348
ReferenceError: reference to undefined property a.Ea.data[Learn More]  fastbutton:386:359
ReferenceError: reference to undefined property _.V.Uc[this.f][Learn More]  cb=gapi.loaded_0:350:56
ReferenceError: reference to undefined property b.cookiepolicy[Learn More]  platform.js:48:32
ReferenceError: reference to undefined property Av[b][Learn More]  rs=AAxzQIWtK5df9yVQvvQ1BbtzLvFGx3heCw:466:301
```

**Comment by Noitidart** [comment] 2016-10-24 01:12
@kvervo Thanks for the at log. Its odd, none of those messages are from foxified. Is the addon enabled?

By the way this was the log to console after you installed the addon, and as Chrome Web Store was loading?

**Comment by Noitidart** [comment] 2016-10-24 01:14
@bluebrainc thanks very much for that! Yep I mean kvervo but this gist helps a lot!

@kvervo after you install the addon you should see in your console the messages seen in the gist posted by bluebrainc.

**Comment by kvervo** [comment] 2016-10-26 19:52
@Noitidart I found the problem. I've enabled 'Always use private browsing mode' after disabling it, everything started working.

**Comment by Noitidart** [comment] 2016-10-26 22:17
Ooo thanks for that @kvervo. I'll close this as duplicate of https://github.com/Noitidart/Chrome-Store-Foxified/issues/36

**Closed by Noitidart** 2016-10-26 22:17 UTC
