### ISSUE TITLE
The new version 3.3 does not work at all

### ISSUE THREAD

**Issue by dimah2005** [Noitidart/Chrome-Store-Foxified#97] opened 2017-11-15 21:54 UTC
I used the former version (I don't know which version) It was fantastic, but now with the current version, it's just freezing at "Preparing to download and install..." or "Validating...", it is completely disappointing.
I tested several extensions (particularly "Multi Search" as an alternative to "web search pro") even I used a CRX file but nothing happened.

updated: I have the problem in two systems (Windows 10, Firefox 57 and 56)

**Comment by seoh** [comment] 2017-11-17 12:04
Latest Firefox of developer edition and beta doesnt works also. (on Ubuntu 17.10)

**Comment by Noitidart** [comment] 2017-11-17 14:17
Interesting, thanks so much for your complements about the old version. Thanks for the detailed tests as well. I'll upload ad debug version please, if you can share with me the console logs that would be great.

**Comment by Noitidart** [comment] 2017-11-22 18:40
I can't reproduce this issue. However I tried signing multi search and validation fails because it uses a banner library (old jquery). You can install it unsigned though. I attached it here for you. I will keep trying to reproduce this bug so I can fix it.
[Multi Search-4.5.2.zip](https://github.com/Noitidart/Chrome-Store-Foxified/files/1497169/Multi.Search-4.5.2.zip)

**Comment by dimah2005** [comment] 2017-12-02 11:10
Thank you a lot for the attachment, 
I've used the addons today again, and it works perfectly, maybe that time the main problem was a server or something like this, I hope never face this problem again. 
thank you

**Comment by Noitidart** [comment] 2017-12-02 14:37
Thanks @dimah2005! If this issue is solved may you please close this issue. :)

**Closed** 2017-12-02 21:39 UTC
